### ISSUE TITLE
Is it compatible with gulp-imagemin?

### ISSUE THREAD

**Issue by oivva** [imagemin/imagemin-zopfli#4]
Have this error:

[00:26:50] TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (D:\Projects\boxy\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:516:8)
    at Gulp.<anonymous> (D:\Projects\boxy\gulpfile.js:369:6)
    at module.exports (D:\Projects\boxy\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\Projects\boxy\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\Projects\boxy\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\Projects\boxy\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Ihor\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
    at Function.Module.runMain (module.js:449:11)

**Comment by shinnn** [comment]
Currently, no.

**Comment by kevva** [comment]
Use a earlier version of `gulp-imagemin` for now. I'll make sure to add support for the latest one shortly :).

**Comment by oivva** [comment]
@kevva Oh, thanks a lot :wink:

**Comment by kevva** [comment]
@oivva, turns out I have converted this already but not released a new version. Could you try now :)?

**Comment by oivva** [comment]
@kevva Thanks again, it works as aspected :cool:

**Comment by kevva** [comment]
Great, happy to hear :).
